[package]
name = "harmonomino"
version = "0.1.0"
edition = "2024"
default-run = "harmonomino"

[dependencies]
rand = "0.9"
ratatui = "0.30"
rayon = "1.10"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "warn"
