[package]
name = "harmonomino"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
ratatui = "0.30"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "warn"
